### PR TITLE
added nested object support to controllers proxy

### PR DESCRIPTION
**Pull request by toondkn**
Reason for this change: some components, like those compatible with the Field component of the Formik library, require nested props.

### CODE REVIEW

**Comment by omarzion** [comment]
Would you mind making your changes in the src folder? 
The files in lib are auto-generated by running npm run build

**Comment by odama626** [comment]
Can you use 2 space indentation to match the current style of the repo and use import instead of require

the diff is too big because of the indentation change for me to really look at the changes beyond that currently

**Comment by toondkn** [comment]
Sure!

**Review by odama626 — APPROVED** [review]

**Comment by odama626** [comment]
Finally got a chance to sit down and properly look over your PR.  It looks good.  I merged it and published 2.0 to npm..  when you get a chance would you mind adding an example of the new nesting functionality in the readme?

**Pull request merged**
